---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/author
  label: Author
  create: documents
  match: "**/*"
- type: directory
  path: content/site
  label: Site
  create: none
  match: "**/*"
  new_doc_ext: json
- type: directory
  path: content/blog
  label: Blog
  create: documents
  match: "**/*"
upload_dir: images
public_path: "/content/blog/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
